upfluence/ember-upf-utils

addon/components/validated-input.js
addon/templates/components/validated-input.hbs
app/components/validated-input.js
tests/integration/components/validated-input-test.js

Define validated input component, to use with ember-cp-validations

---

app/styles/colors.less
app/styles/helpers/colors.less

It's a huge pain to know which color for which social media...

Define social colors

---

addon/components/influencer/profile-description/component.js
addon/components/influencer/profile-description/template.hbs
addon/components/toggle-area/template.hbs
app/styles/components/influencer/profile-description/styles.less
app/styles/components/toggle-area/styles.less

closes https://github.com/upfluence/facade-web/issues/139
I think the `profile-lists` can be rework too

Rework profile description

---

addon/components/layout/left-menu/template.hbs

related to https://github.com/upfluence/facade-web/issues/123

hide navigation menu if user is not authenticated

---

app/styles/colors.less
app/styles/components/progress-radial.less

related to https://github.com/upfluence/inbox-server/pull/40

Add opened color

---

app/styles/components/influencer/profile-description/styles.less

related to https://github.com/upfluence/facade-web/pull/152
before:
after:

Improve display

---

addon/components/layout/left-menu/template.hbs
app/styles/components/left-menu.less
app/styles/layout/left-menu/styles.less
index.js

Add "beta" label on the inbox-web link icon

---

addon/templates/components/currency-chooser.hbs

added thaï baht

---

addon/components/item-chooser/component.js
addon/components/item-chooser/template.hbs
app/components/item-chooser/component.js
app/styles/components/item-chooser.less
tests/integration/components/item-chooser/component-test.js

Move the `item-chooser` component from facade-web to ember-upf-utils

add item-chooser component

---

addon/components/publishr/campaign-dashboard.js
addon/components/toggle-area.js
addon/helpers/format-date.js
app/components/toggle-area.js
app/components/toggle-area/component.js
app/helpers/format-date.js
app/styles/components/publishr/campaign-dashboard.less
app/styles/upf-utils.less
app/templates/components/publishr/campaign-dashboard.hbs
app/templates/components/toggle-area.hbs

To keep consistency and reusability between the publishr-*-web apps, I moved the Campaign Dashboard component there (concerned by Publishr Admin and Publishr Client)

Added some Publishr Campaign related stuffs

---

addon/components/influencer/details-description/component.js
addon/components/influencer/details-description/template.hbs
addon/components/layout/left-menu/component.js
addon/components/layout/left-menu/template.hbs

related to https://github.com/upfluence/inbox-web/issues/71
closes #59

Add inf link and analytics link menu

---

addon/components/layout/app-base/component.js
addon/components/layout/app-base/template.hbs
addon/components/layout/left-menu/component.js
addon/current-user/service.js

Custom logo

---

addon/components/layout/app-base/component.js

Related to https://sentry.io/upfluence/facade-web/issues/282094616/

Ensure extra presence

---

addon/components/layout/left-menu/component.js
addon/components/layout/left-menu/template.hbs

Display help && publishr icon

---

addon/components/ownership-selection/component.js
addon/components/ownership-selection/owner.js
addon/components/ownership-selection/template.hbs
app/components/ownership-selection/component.js
app/styles/components/ownership-selection/styles.less
app/styles/upf-utils.less
tests/integration/components/ownership-selection/component-test.js

Related to : https://github.com/upfluence/oss/pull/26 https://github.com/upfluence/publishr-admin-web/pull/144

Moving Ownership Selection component to Upf-Utils

---

addon/components/file-uploader/component.js
addon/configuration.js

Related to upfluence/uploader-server#6

Use the uplaoder server to handle the uploads

---

addon/helpers/format-timestamp.js
app/helpers/format-timestamp.js
package.json
yarn.lock

This helper is needed in the sidepanel and since the side panel will be in all projects I guess it makes sense to include it in upf-utils. Opinions?

Adding timestamp helper

---

addon/mixins/ajax-errors-serializer.js

Just a fix to use the original errors serializer in case of... And currently this errors serializer doesn't handle camelCase fields.

Rework ajax erros serializer

---

addon/utils/errors-extractor.js

Just a small utils to extract error from ajax payload

Add extract-errors utils

---

addon/components/layout/left-menu/component.js
addon/components/summer-note/component.js
addon/components/summernote-modals/video/component.js
addon/components/summernote-modals/video/template.hbs
addon/components/upf-editor/component.js
addon/components/upf-editor/template.hbs
app/components/summernote-modals/video/component.js
app/components/upf-editor/component.js
package.json
tests/integration/components/summernote-modals/video/component-test.js
tests/integration/components/upf-editor/component-test.js

Related to https://github.com/upfluence/publishr-supplier-web/pull/39

Summernote Video support

---

addon/mixins/has-access-panel.js

Related to: https://github.com/upfluence/facade-web/pull/262

Handle back routes with query params in access panel

---

addon/components/universal-export/component.js
addon/components/universal-export/template.hbs

fix https://sentry.io/upfluence/export-server/issues/571461584/?referrer=slack

Display list only if we are sure that the user can export in

---

addon/mixins/has-access-panel.js
package.json
yarn.lock

Mergeable changes that don't break Ember 2 while making it work with Ember 3.

Ember upgrade related changes

---

addon/components/access-panel.js
app/templates/components/access-panel.hbs

https://github.com/upfluence/oss-components/pull/51

update to match the new oss's upf-table actions hooks

---

addon/components/universal-export/external/component.js
index.js

Register package in the Ember libraries

---

addon/components/ownership-selection-modal/groups/component.js
addon/components/ownership-selection-modal/groups/template.hbs
addon/components/ownership-selection-modal/people/component.js
addon/components/ownership-selection-modal/people/template.hbs
app/styles/components/universal-selection.less
app/templates/components/ownership-selection-modal.hbs

description within ownership selection modal

---

addon/components/ownership-selection-modal/groups/template.hbs
addon/components/ownership-selection-modal/people/template.hbs
addon/components/summernote-modals/pdf/template.hbs
addon/components/summernote-modals/video/template.hbs
addon/components/universal-export/external/template.hbs
addon/components/universal-export/file/template.hbs
addon/components/universal-export/template.hbs
addon/components/upf-editor/template.hbs
addon/components/upgrade-modal/template.hbs
addon/templates/components/modal-view.hbs
app/templates/components/ownership-selection-modal.hbs

- Pass modalTitle into modal view

modal edits

---

.github/workflows/ci.yml

Fixes the CI not running on tags push

fix ci not running on tags push

---

addon/components/influencer/medias-list/template.hbs
app/styles/components/influencer/medias-list/styles.less

Add verified networks to influencer profiles
Part of https://github.com/upfluence/backlog/issues/82
A checkmark will be visible on social media icons if network is verified

Add verified network

---

.eslintrc.js
addon/activity-notifier/service.js
addon/components/feature-flagged/component.js
addon/helpers/format-number.js
addon/utils/filesize-parser.js
tests/integration/components/country-chooser-test.js

Adds a new rule preventing more than 1 blank lines in the code. (https://eslint.org/docs/2.0.0/rules/no-multiple-empty-lines)

eslint: no more than 1 blank line

---

addon/components/upf-editor/component.js
addon/components/upf-editor/template.hbs

Make the height of upf-editor customizable
- [] Added/updated tests

upf-editor: Make the height customizable

---

addon/configuration.js

use hasOwnProperty to check for config property presence

---

package.json

Ship the package w/ ember-keyboard is it's using it internally.
Related : https://github.com/upfluence/backlog/issues/545

Ship w/ ember-keyboard

---

addon/exports/service.js
index.js

Adds an optional max_size parameter to the export call, needed when bulk deleting influencers from the IRM
Related to https://github.com/upfluence/backlog/issues/490
None

Add max size to export service

---

addon/components/http-errors-code/component.js
addon/components/http-errors-code/template.hbs

Use complete url for img
Related to: https://github.com/upfluence/backlog/issues/483

Ember-upf-utils: Use complete url

---

addon/components/http-errors-code/component.js

Fix linter
Related to: https://github.com/upfluence/backlog/issues/483

Ember-upf-utils: Fix linter

---

addon/http-errors/route.js

Add case for unknow route in router
Related to: https://github.com/upfluence/backlog/issues/483

Ember-upf-utils: missing case for random route

---

addon/exports/service.js

Add support to tags payload
Related to: https://github.com/upfluence/backlog/issues/581
Nothing

Add tags support to exports

---

addon/components/influencer/profile-description/component.js
addon/components/influencer/profile-description/template.hbs
app/styles/components/influencer/profile-description/styles.less
translations/en-us.yaml

Add influencer email score to influencer cards
Related to: https://github.com/upfluence/backlog/issues/439

Email Score

---

addon/components/influencer/profile-description/component.js
app/styles/components/influencer/profile-description/styles.less

Visual feedback + bug fixes related to upfluence/backlog#439

Influencer score improvements + bug fixes

---

addon/components/influencer/profile-description/component.js

If no medias is passed to the component, the rest of the page becomes unusable, this makes sure this doesn't happen in that case
The project will remain usable in case influencer medias was not available for some reason

Add safe navigation to influencer media

---

addon/components/table-fluid/component.js
translations/en-us.yaml

Display message in toast when the limit is exceeded during the search
Related to: https://github.com/upfluence/cs/issues/62

Display message when limit is exceeded in infinity scroll

---

addon/components/layout/left-menu/template.hbs
translations/en-us.yaml

This PR adds tooltips to the `left-menu` compoment.
Related to: https://github.com/upfluence/backlog/issues/718

*: add tooltips on the left-menu component

---

.ember-cli
addon/components/influencer/profile-description/component.js
addon/components/influencer/profile-description/template.hbs
app/styles/components/influencer/profile-description/styles.less
index.js
translations/en-us.yaml

Use new tags
Related to: https://github.com/upfluence/backlog/issues/674
In Inbox

Use new tags

---

addon/components/influencer/profile-description/component.js
addon/components/influencer/profile-description/template.hbs

Fixes LDA not being loaded correctly unless sidepanel is open
Related to: https://github.com/upfluence/backlog/issues/768
LDA tags will be hidden in inbox-web as they're not included in the payload

Fix LDA tag not loading correctly

---

addon/exports/service.js

Adds a new "perform" method to the existing Export service.
Related to: https://github.com/upfluence/backlog/issues/815
* Adds a new method that matches the format of the Back-End (also has parameter description in comments)
* Does not change the current definition of the Export service in order to prevent breaking changes in the rest of the projects.

Added: New "perform" method of the export service that matches BE format

---

addon/components/influencer/profile-description/component.js
addon/components/influencer/profile-description/template.hbs
app/styles/components/influencer/profile-description/styles.less
app/styles/components/split-overlay-area/styles.less

Fixes the issue raised by the CS team. 
Related to: https://github.com/upfluence/cs/issues/187
The <img> tag has been replaced by a <div> with css background-image set. This prevents the loading glitch from happening.
The style tag content is created in the component class to prevent XSS warnings.
The default UPF logo/placeholder is set before the picture is loaded and replaced only if the pictureUrl is found.

Profile-description component updated to prevent picture loading glitch in CRM results

---

addon/components/u-edit/shared-modules/drag-and-drop.js
app/styles/components/drag-and-drop.less

Use upload to insert the image in the editor with the generated link
Related to: https://github.com/upfluence/cs/issues/301

Implementation of drag and drop module

---

.github/workflows/ci.yml
.npmrc
addon/components/display-field/template.hbs
addon/components/influencer/profile-description/template.hbs
addon/helpers/format-price.js
addon/mixins/has-access-panel.js
package.json

Migrate to `@upfluence/oss-components`

Use scoped oss-components

---

addon/components/file-uploader/component.js

Added: ability to reset input on validation error with a parameter

Added: ability to reset input on validation error with a parameter

---

addon/notifications/service.js

Added: new fetchFeed endpoint in notification service
Related to: [#1129](https://github.com/upfluence/backlog/issues/1129)

Added: new fetchFeed endpoint in notification service

---

addon/notifications/service.js

Added: notificationFeed service environment notion
Related to: 1129

Added: notificationFeed service environment notion

---

addon/components/layout/left-menu/component.js
addon/components/layout/left-menu/template.hbs

Move workflow as the first app of the software
Related to: https://github.com/upfluence/backlog/issues/1130

Move workflow as the first app of the software

---

addon/components/universal-export.hbs
addon/components/universal-export/file.hbs
addon/components/universal-export/file.js

Fix bugs that came up during the review about the file limit not being correctly handled.
Related to: https://github.com/upfluence/backlog/issues/1211

fix full file export limit bugs

---

addon/components/layout/app-base/template.hbs

Add fx-col to layout for local engine
Related to: https://github.com/upfluence/backlog/issues/1190

Add fx-col to layout for local engine

---

addon/resources/country-codes.js
tests/integration/components/country-chooser-test.js

Updates to the country-code dictionary with the country phone prefixes ; also adds iso3 while we're at it.

Added: new country code dictionary with iso2, iso3 & phone prefixes

---

addon/components/universal-export.ts

Add countKey args to universal-export
Related to: https://github.com/upfluence/cs/issues/509

Add countKey args to universal-export

---

addon/exports/service.js

Fix keyword being double encoded
Related to: [#](https://github.com/upfluence/cs/issues/512)

export searches: fix keyword being double encoded

---

addon/components/layout/left-menu/component.js
addon/components/layout/left-menu/template.hbs
translations/en-us.yaml

Update feature request link
Related to: https://github.com/upfluence/backlog/issues/1371

Update feature request link

---

addon/components/http-errors-code/component.js
addon/components/http-errors-code/template.hbs
addon/components/upgrade-modal/component.js
addon/http-errors/402/controller.js
addon/http-errors/402/template.hbs

Use freshdesk instead of intercom as support channel
Related to https://github.com/upfluence/backlog/issues/1473

Migrate to freshdesk

---

addon/utils/iso-codes.js

Add polish zloty to the supported currencies
Related to: https://github.com/upfluence/backlog/issues/1550

Add polish currency

---

addon/services/activity-watcher.ts
tests/unit/services/activity-watcher-test.ts
yarn.lock

Use new toast service for notifications
Related to: https://github.com/upfluence/backlog/issues/1631

Use new toast service for notifications

---

addon/components/utils/social-media-handle.hbs
addon/components/utils/social-media-handle.ts
app/components/utils/social-media-handle.js
app/styles/components/utils/social-media-handler.less
app/styles/upf-utils.less
package.json
tests/dummy/app/controllers/application.js
tests/dummy/app/styles/app.less
tests/dummy/app/templates/application.hbs
tests/integration/components/utils/social-media-handle-test.ts
translations/en-us.yaml

Adds the new Utiliity component "SocialMediaHandle"
Related to: #[1764](https://github.com/upfluence/backlog/issues/1764)

Adds Utils::SocialMediaHandle

---

app/styles/components/uedit-file-uploader.less

Fix uedit-file-uploader modal's z-index
Related to: #[cs763](https://github.com/upfluence/cs/issues/763)

Fixed: uedit-file-uploader z-index

---

addon/components/universal-export.ts
addon/exports/service.js

Error management in universal export
Related to: https://github.com/upfluence/backlog/issues/1849

Error management in universal export

---

addon/exports/service.js

Re-throw error in export perform function
Related to: https://github.com/upfluence/backlog/issues/1924

Re-throw error in export perform function

---

addon/components/utils/address-form.hbs
addon/components/utils/address-form.ts
package.json
tests/integration/components/utils/address-form-test.ts
yarn.lock

Handle invalid phone numbers when using the dedicated component
Related to: https://github.com/upfluence/cs/issues/756

Handle invalid phone numbers when using the dedicated component

---

addon/components/utils/product-row.ts
tests/integration/components/utils/product-row-test.ts

Ensure dealing with available options
Related to: https://github.com/upfluence/backlog/issues/2055

Ensure dealing with available options

---

addon/components/universal-selection/group/component.js

Remove New tag on live capture group in Import modal
Related to: #https://github.com/upfluence/backlog/issues/2027

Remove New tag on live capture group in Import modal

---

app/styles/bootstrap/jumbotron.less
app/styles/colors.less
app/styles/components/access-panel.less
app/styles/components/http-errors-code.less
app/styles/components/item-chooser.less
app/styles/components/left-menu.less
app/styles/components/publishr/draft-display.less
app/styles/components/spinner.less
app/styles/components/uedit-file-uploader.less
app/styles/components/universal-selection.less
app/styles/helpers/card.less
app/styles/helpers/colors.less
app/styles/helpers/inverse-element.less
app/styles/upf-variables.less

Clean up some less variables
Related to: #

Clean up some less variables

---

app/styles/layout/side-hover-panel/styles.less

Update the transition animation of the side-over panel

Update the transition animation of the side-over panel

---

addon/resources/country-codes.js

Remove USSR from country codes
Related to: https://github.com/upfluence/cs/issues/1195

Remove USSR & European Union from country codes

---

addon/components/utils/social-media-handle.hbs
addon/components/utils/social-media-handle.ts
app/styles/components/utils/social-media-handler.less
tests/dummy/app/templates/application.hbs
tests/integration/components/utils/social-media-handle-test.ts
yarn.lock

Adds @errorMessage parameter on social-media-handle component

Adds @errorMessage parameter on social-media-handle component

---

app/styles/components/access-panel.less
app/styles/layout/side-hover-panel/styles.less
yarn.lock

Uses the `topbar-height` CSS var to fix the access panel & side panel offset

Topbar-related fixes

---

addon/components/layout/app-base/template.hbs
app/styles/layout/app-base/styles.less

Fix layout for new sidebar
Related to: https://linear.app/upfluence/issue/ENG-444/fix-layout-issues

[PLG] Fix layout for new sidebar

---

addon/components/http-errors-code.hbs

Update 404 image link
Related to: https://linear.app/upfluence/issue/ENG-792/default-404-page-of-wednesday-has-broken-formatting

Update 404 image link

---

addon/components/influencer-network-modal.ts
addon/resources/helpdesk-links.ts

It modifies a helpdesk link to point towards a dedicated article for community & influencer management.
https://linear.app/upfluence/issue/ENG-1057/learn-more-in-influencer-network-modal-leads-to-wrong-article

Updated a Help desklink to point towards a dedicated article for Community & influencer Management

---

addon/components/utils/address-form.hbs
addon/components/utils/address-form.ts
app/styles/components/utils/address-form.less
translations/en-us.yaml

Add placeholder for address form
Related to: https://linear.app/upfluence/issue/ENG-1758/certain-fields-background-labels-are-missing

Add placeholder for address form

---

Makefile
addon/components/utils/address-form.hbs
addon/components/utils/address-form.ts
addon/components/utils/product-row.ts
app/styles/components/utils/address-form.less
app/styles/upf-utils.less
config/environment.js
package.json
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/integration/components/utils/address-form-test.ts
translations/en-us.yaml
tsconfig.json
yarn.lock

Google map autocomplete for address form & tests
Related to: https://linear.app/upfluence/issue/ENG-1554/[ember-influencer]-update-influencer-model-and-utilsaddressform

Google map autocomplete for address form & tests

---

config/environment.js
index.js
package.json
yarn.lock

Stop inserting ga script (+ some cleanup)

Stop inserting Analytics script

---

app/styles/vendor/power-select.less
yarn.lock

Related to: #[ENG-778](https://linear.app/upfluence/issue/ENG-778/input-components-update)

Fix power-select for update ui kit 2.0

---

.gitignore
Makefile
index.js
package.json
pnpm-lock.yaml
scripts/generate_sonar_report
sonar-project.properties
tests/test-helper.ts

Enable sonarqube on ember-upf-utils

Enable sonarqube on ember-upf-utils

---

addon/components/utils/social-media-handle.hbs
addon/components/utils/social-media-handle.ts
tests/integration/components/utils/social-media-handle-test.ts
translations/en-us.yaml

Replace twitter by X

---

addon/components/u-edit/shared-triggers/modals/file-uploader.hbs
addon/components/u-edit/shared-triggers/pdf.js
translations/en-us.yaml

Update PDF file uploader

---

addon/http-errors/route.js

Error route: Handle case where error is just a string

---

addon/activity-notifier/service.js

fix: removed instance of upf-icon

---

addon/components/logo-maker.ts

Added: octagon icon in logo-maker

Added: octagon icon in logo-maker

---

addon/components/utils/templated-input-group.hbs

Add fallbackPlacements to templated-input-group

Add fallbackPlacements to templated-input-group

---

app/styles/vendors/flatpickr.less
package.json
pnpm-lock.yaml

Border radius rework

---

.github/workflows/sonarqube-sync.yml

Added: sonarqube wofkflow for CI

Added: sonarqube wofkflow for CI

---

addon/components/format-price/template.hbs

Related to: #[VEL-4660](https://linear.app/upfluence/issue/VEL-4660/httpsdeprecationsemberjscomv3xtoc-this-property-fallback)

Deprecation: Fix property fallback lookup

---

addon/http-errors/route.js

Related to: #[DRA-2849](https://linear.app/upfluence/issue/DRA-2849/404-page-missing-translation)

Fixed 404 missing translation issue

---

addon/components/utils/address-form.hbs
addon/components/utils/social-media-handle.hbs

Related to: #[VEL-4672](https://linear.app/upfluence/issue/VEL-4672/httpsdeprecationsemberjscomv3xtoc-ember-built-in-components-legacy)

Deprecation: Fix built-in components legacy attributes

---

addon/components/utils/jace-blob.hbs
addon/components/utils/jace-blob.ts
app/components/utils/jace-blob.js
app/styles/components/jace-blob.less
app/styles/upf-utils.less
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/integration/components/utils/jace-blob-test.ts

Added the Jace blob component. It has 2 gifs & an animation overlay in CSS for the active & Idle states ( cf loom below ) 
turns out I added a layer of logic for timing gifs , but it got in the way when we went to animate the borders, but the cross fade makes the transition pretty seemless 
Related to: #
https://www.loom.com/share/dd476d81757643a398c0b986711c68cc?sid=9db5a53d-c92a-4e39-a69b-48c3142da128

Feature: Jace blob

---

addon/components/upgrade-modal.js
addon/configuration.js
addon/decorators/deactivated-account-handler.js

Target new settings URL / route

Target new settings URL / route
