upfluence/ember-upf-utils

- addon/components/layout/side-hover-panel/component.js
Related to upfluence/facade@0238271
With the new ember glimmer tree the side-hover panel does not go away when we go to an other route
I add an explicit deletion of the node
> Get rid of the node added to the dom in the willDestroyElement callback

- addon/components/file-uploader/component.js
- addon/components/file-uploader/template.hbs
- addon/components/input-uploader/component.js
- app/styles/components/file-uploader.less
A rework to a better use of the file uploader.
This Pr add a twostep option to split the process in two (see screen shot) to avoid the auto upload:
`Upload` trigger the upload or the `arrow` return to the default state.
I have add a front extension checker to avoid upload file if the extension is wrong. In this case with or without the `twostep` the upload will be stop and this view is display:
Front validation are bubbled with `didValidationError` 
Since progress bar don't work very well, I have add a option to hide it by default.
All of this is for a better errors handler on front and use translations based on errors from backend
> Rework upload-file

- addon/templates/components/loading-spinner.hbs
@tgallice this is the reason of the horizontal scroll bar in the Facade list page.
Cc. @phndiaye & @tgallice could it break any other compatibility? (i.e. `table-fluid`?)
> Get rid of the container div wrapper around the spinner

- addon/components/summer-note/component.js
- addon/components/upf-editor/component.js
Use Summernote's plugin system for our custom buttons instead of just pushing them in the toolbar. This fixes the issue with custom buttons stacking up after navigation because they were not properly destroyed with the Summernote Instance.
> Use Summernote's plugin system for the custom buttons

- addon/components/publishr/draft-display/medias/template.hbs
This issue comme from jhonayce, video from draft won't work correctly here is an exemple: https://software.upfluence.co/client/campaigns/mbp-christmas-pl-771/drafts/mbp-christmas-pl-christophermakowski-98352
I remove the type with is `application/octet-stream` for the exemple and this lead to the issue IMO. Without the type, the bowser guess with the file. 
@phndiaye can you check on this ? Do you see something wrong ?
> Remove the type and let guess it

- addon/components/summernote-modals/pdf/component.js
> Summernote: display embedded pdfs with html embed tag and not via Google's viewer

- addon/components/universal-export/external/template.hbs
- addon/components/universal-selection/component.js
- addon/components/universal-selection/template.hbs
@leanminmachine added this for the universal selection, it's optional but needed in publishr/analytics. for the import can you help do the update to pass the labels ? it's for a better understanding of what the selection does :)
> universal-selection: allow label on the power-select

- addon/components/ownership-selection-modal.js
- addon/components/ownership-selection-modal/people/component.js
- app/templates/components/ownership-selection-modal.hbs
when a different note is selected after a note was selected, the different note should not have the preselected ownership entity from the original note shown.
> reload selected users with entity change, for notes

- addon/components/layout/left-menu/component.js
On the side bar, their icons do not have the 'active' state when you select them
> Fix active state on facade, publishr-client, analytics

- addon/components/influencer-network-modal/component.js
- addon/components/influencer-network-modal/template.hbs
- addon/components/universal-export/component.js
- addon/components/universal-export/external/template.hbs
- addon/components/universal-export/template.hbs
- app/components/influencer-network-modal/component.js
- app/styles/bootstrap/modal.less
- tests/integration/components/influencer-network-modal/component-test.js
- translations/en-us.yaml
Adds a validation modal to inform user that selected influencers have been added to their influencer network.
https://github.com/upfluence/backlog/issues/27
A modal with more information about influencer network will now be displayed after a user exports a list of influencers
> Add validation modal to universal export

- addon/components/country-chooser.js
This fixes a bug in the CountryChooser component not having an initial selection even though the `countryCode` or `countryCodes` (if multiple selection) named arguments have values.
Fixes #
> CountryChooser: fix _selection not being assigned on initial loa even w/ countryCode(s) not being empty

- addon/components/age-bracket-chooser/component.js
- addon/components/age-bracket-chooser/template.hbs
Fixes the age bracket chooser not updating the attribute it was passed down in its parent anymore.
DDAU* = Data Down Actions Up https://emberigniter.com/ddau-data-owner-mutate/
The `age-bracket-chooser` component has only one usage occurence in facade-web in the codebase.
Part of https://github.com/upfluence/backlog/issues/352
When selecting a value, the change is passed onto the parent component/controller/route via an action.
> Fix age bracket chooser not passing up the mutated age bracket (DDAU impl)

- addon/components/modal-view.js
Fixes the closeModal function not being called on Esc keydown.
(my two cents is that there is a listener on it in bootstrap via jQuery)
Related : https://github.com/upfluence/backlog/issues/329
> modal-view : fix uncatched escape key

- addon/components/ownership-selection-modal/groups/component.js
- addon/components/ownership-selection-modal/groups/template.hbs
- addon/components/ownership-selection/component.js
- addon/components/ownership-selection/template.hbs
- app/templates/components/ownership-selection-modal.hbs
- package.json
- tests/integration/components/ownership-selection-test.js
- tests/test-helper.js
Fix the ownership selection being uncorrectly built off the entity itself 🤔  
Introduces the use fo [Sinon.js](https://sinonjs.org/) in testing. It's a really good library for stubs & mocks (based off what i read + recommendations in the Ember community). Why? Because even if Ember has support for creating stubs (for services for example), we can't stub a call to method to return what we want.
PS : This is based off my current knowledge of the testing features ahah 😅 
Related https://github.com/upfluence/backlog/issues/408
Useful Resource : [Ember Octane vs Classic Cheat …
> Ownership-selection: fix group selection

- addon/components/universal-export/create-item/template.hbs
Universal export buttons were invisible until user hovers on them
Related to https://github.com/upfluence/backlog/issues/486
Buttons will always be visible
> Fix universal export buttons

- addon/components/universal-export/create-item/template.hbs
Removing btn class breaks btn-group style, an alternate solution was found so this PR adds the class back
> Add btn class to buttons to maintain btn-group style

- addon/components/smart-link-to.hbs
Fix missing @ before argument, after migrating to new syntax
None
> Fix argument syntax

- addon/components/table-fluid/component.js
Add condition to avoid extra call for match endpoint make by ember-infinity. Skeleton at the end of short search (ex: 22 influencers) isn't displayed now 
Related to: https://github.com/upfluence/backlog/issues/528
No extra loading skeleton for search
> Ember-upf-utils : Disabled the search skeleton display

- addon/components/age-bracket-chooser/component.js
- app/templates/components/country-chooser.hbs
Updates dataAttributes of two components so that we can pass 'data-control-name' attributes as parameters
Related to: https://github.com/upfluence/backlog/issues/657
- Updated _country-choser_ component with Glimmer splattributes
- Updated _age-bracket-choser_ component with an attributeBindings param named 'data-control-name'
> Small Component Updates to allow "data-control-name" attributes to be passed as parameters

- addon/components/u-edit/pdf-upload.hbs
- addon/components/u-edit/pdf-upload.js
- app/components/u-edit/pdf-upload.js
- tests/integration/components/u-edit/pdf-upload-test.js
- translations/en-us.yaml
Adds necessary modal needed to upload PDF
Related to: https://github.com/upfluence/uedit/pull/16
A modal that supports PDF files and sends back the URL after uploading
> Add UEdit PDF Upload Modal

- app/styles/components/publishr/draft-display.less
Big image broke the rendering of draft. This will ensure that the images didn't overflow the container.
> draft-display: Ensure that draft images doesn't overflow the container

- addon/components/u-edit/shared-triggers/modals/image-upload.hbs
- app/styles/components/image-upload-modal.less
After the user uploaded an image to be added to the editor, show info about the filename.
Related to: https://github.com/upfluence/backlog/issues/809
> Shared Triggers/Image modal: Show feedbacks about the uploaded file

- addon/activity-notifier/service.js
Handle `credential_disconnected` notification
Related to: https://github.com/upfluence/backlog/issues/824
should we add `integration` between "Your" & "{{integration_name}}" ??
> Handle integration disconnected alert

- addon/components/u-edit/shared-triggers/modals/file-uploader.hbs
Add maximum PDF size to uedit PDF uploader
Related to: https://github.com/upfluence/cs/issues/199
None
> Add maximum PDF size

- addon/exports/service.js
- Stop passing access token through the URL parameters and use the `Authorization` header instead.
Related to https://github.com/upfluence/backlog/issues/1010
> Pass access token through headers instead of url params

- addon/utils/access-panel.js
- app/styles/layout/side-hover-panel/styles.less
- app/utils/access-panel.js
In order to move a way from the Mixin pattern (that's not usable on Glimmer components for example), this moves the code from the [`HasAccessPanelMixin`](https://github.com/upfluence/ember-upf-utils/blob/master/addon/mixins/has-access-panel.js) to a utility class that needs to be instantiated.
It's usage can be found here:
- https://github.com/upfluence/publishr-admin-web/pull/394/files#diff-c47d147603435e492066d5b65f1d2336b45b535baaec312edbe1966acb431d6dR31
- https://github.com/upfluence/publishr-admin-web/pull/394/files#diff-0943c0bf98078b0b972e31312f77858776ddaf642958254f6f3ce8a767dc512eR50
Related to: https://github.com/upfluence/backlog/issues/1120
* Feel free to migrate existing components to Glimmer …
> Add access panel utility class to move away from the mixin

- package.json
- yarn.lock
Accidentally noticed that `oss-components` was being setup by all projects including in their dependencies, causing weird behaviour where Font Awesome pro assets where not included because the last parent app was ember-upf-utils and not publishr-admin-web for example.
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies
> move oss-components to peerDependencies

- addon/components/universal-selection/component.js
Display Live Capture campaigns at the top of the entities in the universal-selection component to showcase it.
Related to:  https://github.com/upfluence/backlog/issues/1193
> universal-section: display acquisition campaigns to the top

- addon/components/universal-export/file.hbs
- translations/en-us.yaml
Migrate upf-alert to OSS::Alert component
Related to: https://github.com/upfluence/backlog/issues/1683
See slack channel
> Migrate upf-alert to OSS::Alert component

- addon/components/influencer/profile-description.hbs
Adds a tooltip on the LDA profile description tag
Related to: #[1804](https://github.com/upfluence/backlog/issues/1804)
> Adds a tooltip on the LDA profile description tag

- addon/components/influencer-network-modal.hbs
- addon/components/influencer-network-modal.js
- addon/components/universal-export/external/component.js
- addon/components/universal-export/external/template.hbs
- tests/integration/components/universal-export-test.ts
Wherever we needed to display the influencer network modal, we need to ensure first that the current user is not using
the bracket-based billing format.
Related to: [#1850](https://github.com/upfluence/backlog/issues/1850)
> Conditionally  display modal

- addon/exports/service.js
When the perform method of export service is called, catch the possible errors and route them to the communityThresholdManager.
Related to: #[1849](https://github.com/upfluence/backlog/issues/1849)
> Added: catch export error and route it to communityThresholdManager

- addon/components/utils/address-form.ts
- tests/integration/components/utils/address-form-test.ts
Fixes a bug where if you choose a country without mandatory state and fill it, then switch to a country with mandatory state, the previous State value is kept but the input is replaced with an `OSS::ProvinceSelector`, leading to the form being considered as valid while the UI displays no state.
> utils/address-form: always reset the state field when the country is updated

- addon/components/age-bracket-chooser/component.js
Changes a tiny trad on age picker
Related to: #
https://linear.app/upfluence/issue/ENG-1161/[facade-web]-disable-search-features-for-wednesday-users
> Changed translation for age bracket chooser

- addon/components/utils/address-form.hbs
- addon/components/utils/address-form.ts
- tests/integration/components/utils/address-form-test.ts
Add `hidePhoneNumber` arg for address form component
Related to: https://linear.app/upfluence/issue/ENG-1564/[ember-influencer]-new-attributespanelshippingaddress-component-and
> Add hidePhoneNumber arg for address form component

- addon/components/utils/address-form.hbs
- addon/components/utils/address-form.ts
- tests/dummy/app/templates/application.hbs
- tests/integration/components/utils/address-form-test.ts
Add custom key for address form. This update is necessary because the backend send to us in compensation-shipping-address the field `address1` and `line1` for shipping address in the influencer model
Related to: https://linear.app/upfluence/issue/ENG-1564/[ember-influencer]-new-attributespanelshippingaddress-component-and
> Add custom key for address form

- addon/components/utils/address-form.ts
- tests/integration/components/utils/address-form-test.ts
Fix validated address form fields:
The bug appears when no `phone` is present in the address and the `@hidePhoneNumber` is true. The validator return false because the `phone` is present in `BASE_VALIDATED_ADDRESS_FIELDS`. During the validation the `isEmpty(this.args.address.phone)` always fails.
Related to: https://linear.app/upfluence/issue/ENG-1756/mandatory-requirement-for-fields-are-not-respected
> Fix validation for address form fields

- addon/components/utils/address-form.hbs
- translations/en-us.yaml
Address form placeholder update
Related to: https://linear.app/upfluence/issue/ENG-1784/accept-offer-modal-is-missing-certain-field-labels
> Address form placeholder update

- package.json
- pnpm-lock.yaml
- tests/dummy/app/routes/application.ts
- tests/integration/components/u-edit/shared-triggers/modals/image-upload-test.js
- tests/integration/components/u-edit/shared-triggers/modals/pdf-upload-test.js
- tests/integration/components/utils/address-form-test.ts
- tests/integration/components/utils/social-media-handle-test.ts
- tests/integration/components/utils/utm-link-builder-test.ts
Related to: #[VEL-2179](https://linear.app/upfluence/issue/VEL-2179/upgrade-ember-intl-to-v6)
> Ember-intl: Migrate to v6.4

- addon/components/http-errors-code.hbs
- addon/components/http-errors-code.ts
- addon/http-errors/template.hbs
- tests/integration/components/http-errors-code-test.ts
- translations/en-us.yaml
This PR updates the look of the default error page, to match 404 et 500 error pages' design
When we encounter a server error other than 404 or 500, the new default error page is displayed.
Works for Upfluence and Wednesday.
> Hc/vel 2958/generic error page rework

- addon/activity-notifier/service.js
- addon/components/feature-flagged/template.hbs
- addon/mixins/activity-runner.js
- package.json
- pnpm-lock.yaml
- tests/dummy/config/targets.js
Remove unused ember-tether as the addon is not really using it.
This must be merged after: https://github.com/upfluence/ember-influencer/pull/572 & https://github.com/upfluence/hypertable/pull/208
> [VEL-3593/VEL-3588]  Remove unused ember-tether

- addon/services/activity-watcher.ts
- tests/unit/services/activity-watcher-test.ts
- translations/en-us.yaml
Updated wording of email received notification, transferred all notifications' text to the translation file, updated tests.
Related to: #[DRA-27](https://linear.app/upfluence/issue/DRA-27/[plg]-reply-button-toast-message-does-not-appear-on-new-line)
> Updated: wording for email received toast + intl

- addon/http-errors/402/controller.js
- pnpm-lock.yaml
Related to: #[VEL-3591](https://linear.app/upfluence/issue/VEL-3591/httpsdeprecationsemberjscomv3xtoc-routing-transition-methods)
> Replace usage of this.transitionTo

- addon/services/activity-watcher.ts
- tests/unit/services/activity-watcher-test.ts
ActivityWatcher now disconnects users when token_destroyed is received
> ActivityWatcher now disconnects users when token_destroyed is received

- addon/components/utils/address-inline.hbs
- addon/components/utils/address-inline.ts
- app/components/utils/address-inline.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/utils/address-inline-test.ts
- translations/en-us.yaml
Create new address inline with Google place API. This component is inspired by the `Utils::AddressForm` component
> Create new address inline with Google place API

- addon/components/u-edit/shared-triggers/modals/file-uploader.hbs
- addon/components/utils/address-form.hbs
- addon/components/utils/social-media-handle.hbs
Removed "@" on placeholder argument on Input components, as this is now deprecated.
Also, Prettier.
Related to: #[VEL-4671](https://linear.app/upfluence/issue/VEL-4671/httpsdeprecationsemberjscomv3xtoc-ember-built-in-components-legacy)
> [ember-upf-utils] Removed deprecated @placeholder argument on Input

- .github/workflows/ci.yml
- addon/components/utils/utm-link-builder.hbs
- addon/components/utils/utm-link-builder.ts
- app/styles/components/utm-link-builder.less
- tests/integration/components/utils/utm-link-builder-test.ts
- translations/en-us.yaml
Update utm-link-builder to match new designs/specs to:
- use the `OSS::TogglableSection` component
- update the style of the mandatory field "*" marker
- add some validation on inputs' blur event
- allow the preview to be disabled (enabled by default for BC)
TODO:
- double check usage in workflow app
- might need to allow validation errors to be passed as args too when the validation is done by the upper level
> Update utm-link-builder to match new designs/specs

- addon/components/utils/templated-input-group.hbs
- addon/components/utils/templated-input-group.ts
UTM variables dropdown could not be closed by clicking again on the insert variables link. This PR fixes the issue
Related to: #
https://github.com/user-attachments/assets/9c03c6bc-bfa5-44a6-a8c7-e1fd9cc30a35
> Fix insert variable link

- addon/components/utils/templated-input-group.hbs
- app/styles/components/utils/templated-imput-group.less
- app/styles/upf-utils.less
- tests/integration/components/utils/templated-input-group-test.ts
Fix templated input group offset dropdown
> Fix templated input group offset dropdown

- addon/components/utils/address-form.hbs
- addon/components/utils/address-form.ts
- tests/integration/components/utils/address-form-test.ts
Added: Ability to focus AddressForm component inputs from parent
Some screenshot examples from the side-panel:
> Added: Ability to focus AddressForm component inputs from parent

- addon/components/utils/jace-blob.hbs
Add a "/" to the image URLs of Jace Blob component to make it usable in engines.
Component's tests were not affected.
Related to: #[dra-3336](https://linear.app/upfluence/issue/DRA-3336/publishr-admin-web-new-campaign-creation-style-selection-modal)
> Fixed jace blob image urls

- addon/components/u-edit/shared-triggers/modals/file-uploader.hbs
- package.json
- pnpm-lock.yaml
Fixed change in label styling following removal of bootstrap classes in oss-components.
Related to: #[vel-5926](https://linear.app/upfluence/issue/VEL-5926/ember-upf-utils-check-label-elements-design-for-unwanted-changes)
> Fixed ember-upf-utils label to match design

- addon/components/utils/address-form.ts
AddressForm - Use model getter for safe access to computed property
In the address form, when the user does not use the GOOGLE API autocompletion, it is currently impossible to add any other (non-autocomplete related) data.
The reason is that the following error from being raised when the input listener is triggered:
Using the model's `get` method, we ensure we have a proper access to the attribute.
> AddressForm - Use model getter for safe access to computed property
